# Generated by Django 4.0.6 on 2022-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Movie_description', models.TextField()),
                ('Movie_Year', models.IntegerField()),
            ],
        ),
    ]
