# Generated by Django 4.0.6 on 2022-08-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Movie_Img',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Movie_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Movie_Year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Movie_description',
            new_name='description',
        ),
    ]
