# Generated by Django 4.0.6 on 2022-08-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_movie_img_movie_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Img',
            new_name='Movie_Img',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Name',
            new_name='Movie_Name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='Movie_Year',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='Movie_description',
        ),
    ]
