# Generated by Django 4.0.6 on 2022-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_movies_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Movie_Img',
        ),
        migrations.AddField(
            model_name='movies',
            name='Movie_img',
            field=models.ImageField(default='dgdg', upload_to='pic'),
            preserve_default=False,
        ),
    ]
